/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class AClassWithNativeMethods */

#ifndef _Included_AClassWithNativeMethods
#define _Included_AClassWithNativeMethods
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     AClassWithNativeMethods
 * Method:    theNativeMethod
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_AClassWithNativeMethods_theNativeMethod
  (JNIEnv *, jobject, jstring);

#ifdef __cplusplus
}
#endif
#endif
