app:
  kafka:
    bootstrap-servers: concsys.collaud.me:29092
    consumer-group-name: simon-barras-01
  cdc-topic: tp3-cdc-data
  command-topic: tp3-cdc-command

quarkus:
  devservices:
    enabled: false
  shutdown:
    timeout: PT10S
  native:
    container-build: true
  console:
    color: true
  swagger-ui:
    enable: true
  http:
    port: 8080