version: '3'
services:
  gateway:
    image: registry.forge.hefr.ch/si-ii-tp-groupe6-22-23/si-ii-tp2-groupe6-22-23/gateway:latest
    ports:
      - "8080:8080"

  rating-rest:
    image: registry.forge.hefr.ch/si-ii-tp-groupe6-22-23/si-ii-tp2-groupe6-22-23/rating-rest:latest
    ports:
      - "8081:8081"

  drink-rest:
    image: registry.forge.hefr.ch/si-ii-tp-groupe6-22-23/si-ii-tp2-groupe6-22-23/drink-rest:latest
    ports:
      - "8082:8082"

  svelte-frontend:
    image: registry.forge.hefr.ch/si-ii-tp-groupe6-22-23/si-ii-tp2-groupe6-22-23/frontend-svelte:latest
    ports:
      - "3000:3000"
