package net.collaud.gaetan.kafka.rainaggregator.koala.type;

public enum MetricType {
  AIR_TEMPERATURE_C,
  GROUND_TEMPERATURE_C,
  AIR_HUMIDITY_PERCENT,
  WET_TEMPERATURE_C,
  DEW_POINT_C,
  GROUND_RESISTANCE_OHM,
  GROUND_HUMIDITY_CBAR,
  WIND_DIRECTION_DEGR,
  WIND_SPEED_KMH,
  WIND_GUST_SPEED_KMH,
  RAIN_MM,
  PRESSURE_HPA,
  PM10_UG_M3,
  PM25_UG_M3,
  AIR_QUALITY_INDEX,
  DISTANCE_MM,
  LEAF_WETNESS_COUNT,
  RSSI,
  SNR,
  SPREAD_FACTOR,
  BATTERY_VOLT,
  BATTERY_PERCENT,

  // AGGREGATE
  AGGREGATE_RAIN_MM_24H,

  // COMPUTED
  HEIGHT_MM,

  // Mecano specific
  TIMESTAMP_SEC,
}
