version: '3.9'
services:
  backend:
    container_name: dotnet-api
    image: registry.forge.hefr.ch/si-ii-tp-groupe6-22-23/si-ii-tp1-groupe6-dotnet-22-23:latest
    restart: always
    ports:
      - 80:8080
    depends_on:
      - mysql
  mysql:
    container_name: mysql
    image: mysql:5.7
    restart: always
    environment:
      MYSQL_DATABASE: 'db'
      # Password for root access
      MYSQL_ROOT_PASSWORD: 'password'
    ports:
      # <Port exposed> : < MySQL Port running inside container>
      - 3306:3306
    expose:
      # Opens port 3306 on the container
      - 3306
      # Where our data will be persisted
    volumes:
      - /home/ubuntu/docker/mysql:/var/lib/mysql