FROM ubuntu:18.04

RUN apt-get update
RUN apt-get -y upgrade
RUN apt-get install -y wget
RUN mkdir temp
WORKDIR temp
RUN wget https://downloads.apache.org/ant/binaries/apache-ant-1.10.11-bin.tar.gz
RUN wget https://repo1.maven.org/maven2/ant-contrib/ant-contrib/1.0b3/ant-contrib-1.0b3.jar

FROM maven:latest

RUN mkdir ant
WORKDIR ant
COPY --from=0 /temp/apache-ant-1.10.11-bin.tar.gz .
RUN tar -xvf apache-ant-1.10.11-bin.tar.gz
RUN ln -s  /ant/apache-ant-1.10.11/bin/ant /usr/bin/ant
RUN export ANT_HOME=/ant/apache-ant-1.10.1
WORKDIR /ant/apache-ant-1.10.11/lib
COPY --from=0 /temp/ant-contrib-1.0b3.jar .

WORKDIR /
RUN mkdir placeholderproject
WORKDIR placeholderproject
COPY docker/minimal_pom.xml	pom.xml

RUN mvn site
RUN mvn javadoc:javadoc
RUN mvn checkstyle:checkstyle
RUN mvn compile



