/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class ShowWinInfo */

#ifndef _Included_ShowWinInfo
#define _Included_ShowWinInfo
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     ShowWinInfo
 * Method:    getWinInfo
 * Signature: ()Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_ShowWinInfo_getWinInfo
  (JNIEnv *, jclass);

#ifdef __cplusplus
}
#endif
#endif
