image: maven:3.8.6-eclipse-temurin-19-alpine

stages:
  - compile
  - test
  - deploy

compile:
  stage: compile
  script:
    - echo "Compiling"
    - mvn compile
    - echo "Compilation complete"
  artifacts:
    paths:
      - /target

test:
  stage: test
  script:
    - echo "Testing"
    - mvn test
    - echo "Testing complete"


deploy:
  image: docker:19.03
  stage: deploy
  only:
    - develop
    - main
  variables:
    DOCKER_DRIVER: overlay2
  services:
    - docker:19.03-dind
  script:
    ## define variables
    - export CI_REGISTRY_IMAGE=registry.forge.hefr.ch/si-ii-tp-groupe6-22-23/si-ii-tp1-groupe6-spring-22-23
    - export CI_REGISTRY=registry.forge.hefr.ch
    ## publishing
    - echo 'Publishing Spring Docker image'
    - docker login ${CI_REGISTRY} -u nicolas.terreaux -p ${CI_BUILD_TOKEN}
    - docker build . -t ${CI_REGISTRY_IMAGE}:latest --network=host
    - docker push ${CI_REGISTRY_IMAGE}:latest






