############################
# STEP 1 build executable binary
############################
FROM golang:alpine AS builder
# Install git.
# Git is required for fetching the dependencies.
RUN apk update && apk add --no-cache git upx
WORKDIR $GOPATH/src/mypackage/myapp/
COPY 01_kubernetes/fibonacci-application-go/ .
# Fetch dependencies.
# Using go get.
RUN go get -d -v
# Build the binary.
RUN CGO_ENABLED=0 GOARCH=amd64 GOOS=linux go build -ldflags="-w -s" -o /go/bin/fibonacci
# Compress the binary
RUN upx --brute /go/bin/fibonacci
############################
# STEP 2 build a small image
############################
FROM scratch
EXPOSE 8080
# Copy our static executable.
COPY --from=builder /go/bin/fibonacci /go/bin/fibonacci
# Run the fibonacci binary.
ENTRYPOINT ["/go/bin/fibonacci"]