apiVersion: apps/v1
kind: Deployment
metadata:
  name: frontend
  namespace: pi-gr4
spec:
  replicas: 1
  selector:
    matchLabels:
      app: frontend
  template:
    metadata:
      labels:
        app: frontend
    spec:
      imagePullSecrets:
        - name: regcred
      containers:
        - image: registry.forge.hefr.ch/nicolas.terreaux/2223-pi-gr4/frontend:${TAG}
          name: frontend
          ports:
            - containerPort: 80
              name: http
              protocol: TCP
---
apiVersion: v1
kind: Service
metadata:
  name: frontend-svc
  namespace: pi-gr4
spec:
  ports:
    - name: http
      protocol: TCP
      port: 80
      targetPort: 80
  selector:
    app: frontend
  type: ClusterIP
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: frontend-http
  namespace: pi-gr4
  annotations:
    kubernetes.io/ingress.class: nginx
spec:
  rules:
    - host: app.${URL}
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: frontend-svc
                port:
                  number: 80
