apiVersion: apps/v1
kind: Deployment
metadata:
  name: backend
  namespace: pi-gr4
spec:
  replicas: 1
  selector:
    matchLabels:
      app: backend
  template:
    metadata:
      labels:
        app: backend
    spec:
      imagePullSecrets:
        - name: regcred
      containers:
        - image: registry.forge.hefr.ch/nicolas.terreaux/2223-pi-gr4/backend:${TAG}
          name: backend
          ports:
            - containerPort: 3000
              name: http
              protocol: TCP
          livenessProbe:
            httpGet:
              path: /api/v1/health
              port: 3000
            initialDelaySeconds: 150
            periodSeconds: 10
          readinessProbe:
            httpGet:
              path: /api/v1/health/db
              port: 3000
            initialDelaySeconds: 150
            periodSeconds: 10
---
apiVersion: v1
kind: Service
metadata:
  name: backend-svc
  namespace: pi-gr4
spec:
  ports:
    - name: http
      protocol: TCP
      port: 80
      targetPort: 3000
  selector:
    app: backend
  type: ClusterIP
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: backend-http
  namespace: pi-gr4
  annotations:
    kubernetes.io/ingress.class: nginx
spec:
  rules:
    - host: app.${URL}
      http:
        paths:
          - path: /api
            pathType: Prefix
            backend:
              service:
                name: backend-svc
                port:
                  number: 80
